from enum import Enum


class ActivityCode(str, Enum):
    # -------- AUTH --------
    LOGIN = "LOGIN"
    LOGOUT = "LOGOUT"

    # -------- USERS --------
    CREATE_USER = "CREATE_USER"
    UPDATE_USER_ROLE = "UPDATE_USER_ROLE"
    UPDATE_USER_EMAIL = "UPDATE_USER_EMAIL"
    UPDATE_USER_PASSWORD = "UPDATE_USER_PASSWORD"
    ACTIVATE_USER = "ACTIVATE_USER"
    DEACTIVATE_USER = "DEACTIVATE_USER"
    REACTIVATE_USER = "REACTIVATE_USER"

    # -------- CUSTOMERS --------
    CREATE_CUSTOMER = "CREATE_CUSTOMER"
    UPDATE_CUSTOMER = "UPDATE_CUSTOMER"
    DEACTIVATE_CUSTOMER = "DEACTIVATE_CUSTOMER"
    REACTIVATE_CUSTOMER = "REACTIVATE_CUSTOMER"

    # -------- SUPPLIERS --------
    CREATE_SUPPLIER = "CREATE_SUPPLIER"
    UPDATE_SUPPLIER = "UPDATE_SUPPLIER"
    DEACTIVATE_SUPPLIER = "DEACTIVATE_SUPPLIER"
    REACTIVATE_SUPPLIER = "REACTIVATE_SUPPLIER"

    # -------- PRODUCTS --------
    CREATE_PRODUCT = "CREATE_PRODUCT"
    UPDATE_PRODUCT = "UPDATE_PRODUCT"
    DEACTIVATE_PRODUCT = "DEACTIVATE_PRODUCT"
    REACTIVATE_PRODUCT = "REACTIVATE_PRODUCT"

    # -------- INVENTORY --------
    CREATE_LOCATION = "CREATE_LOCATION"
    UPDATE_LOCATION = "UPDATE_LOCATION"
    DEACTIVATE_LOCATION = "DEACTIVATE_LOCATION"
    REACTIVATE_LOCATION = "REACTIVATE_LOCATION"
    INVENTORY_MOVEMENT = "INVENTORY_MOVEMENT"

    # -------- GRN --------
    CREATE_GRN = "CREATE_GRN"
    UPDATE_GRN = "UPDATE_GRN"
    VERIFY_GRN = "VERIFY_GRN"
    DELETE_GRN = "DELETE_GRN"
    