from enum import Enum


class ActivityCode(str, Enum):
    # -------- AUTH --------
    LOGIN = "LOGIN"
    LOGOUT = "LOGOUT"

    # -------- USERS --------
    CREATE_USER = "CREATE_USER"
    UPDATE_USER_ROLE = "UPDATE_USER_ROLE"
    UPDATE_USER_EMAIL = "UPDATE_USER_EMAIL"
    UPDATE_USER_PASSWORD = "UPDATE_USER_PASSWORD"
    ACTIVATE_USER = "ACTIVATE_USER"
    DEACTIVATE_USER = "DEACTIVATE_USER"
    REACTIVATE_USER = "REACTIVATE_USER"

    # -------- CUSTOMERS --------
    CREATE_CUSTOMER = "CREATE_CUSTOMER"
    UPDATE_CUSTOMER = "UPDATE_CUSTOMER"
    DEACTIVATE_CUSTOMER = "DEACTIVATE_CUSTOMER"
    REACTIVATE_CUSTOMER = "REACTIVATE_CUSTOMER"

    # -------- SUPPLIERS --------
    CREATE_SUPPLIER = "CREATE_SUPPLIER"
    UPDATE_SUPPLIER = "UPDATE_SUPPLIER"
    DEACTIVATE_SUPPLIER = "DEACTIVATE_SUPPLIER"
    REACTIVATE_SUPPLIER = "REACTIVATE_SUPPLIER"

    # -------- PRODUCTS --------
    CREATE_PRODUCT = "CREATE_PRODUCT"
    UPDATE_PRODUCT = "UPDATE_PRODUCT"
    DEACTIVATE_PRODUCT = "DEACTIVATE_PRODUCT"
    REACTIVATE_PRODUCT = "REACTIVATE_PRODUCT"

    # -------- INVENTORY --------
    CREATE_LOCATION = "CREATE_LOCATION"
    UPDATE_LOCATION = "UPDATE_LOCATION"
    DEACTIVATE_LOCATION = "DEACTIVATE_LOCATION"
    REACTIVATE_LOCATION = "REACTIVATE_LOCATION"
    INVENTORY_MOVEMENT = "INVENTORY_MOVEMENT"

    # -------- GRN --------
    CREATE_GRN = "CREATE_GRN"
    UPDATE_GRN = "UPDATE_GRN"
    VERIFY_GRN = "VERIFY_GRN"
    DELETE_GRN = "DELETE_GRN"

    # -------- QUOTATIONS --------
    CREATE_QUOTATION = "CREATE_QUOTATION"
    UPDATE_QUOTATION = "UPDATE_QUOTATION"
    APPROVE_QUOTATION = "APPROVE_QUOTATION"
    CONVERT_QUOTATION_TO_INVOICE = "CONVERT_QUOTATION_TO_INVOICE"
    DELETE_QUOTATION = "DELETE_QUOTATION"
    CANCEL_QUOTATION = "CANCEL_QUOTATION"
    EXPIRE_QUOTATION = "EXPIRE_QUOTATION"

    # -------- INVOICES --------
    CREATE_INVOICE = "CREATE_INVOICE"
    UPDATE_INVOICE = "UPDATE_INVOICE"
    APPLY_DISCOUNT = "APPLY_DISCOUNT"
    OVERRIDE_DISCOUNT = "OVERRIDE_DISCOUNT"
    VERIFY_INVOICE = "VERIFY_INVOICE"
    ADD_PAYMENT = "ADD_PAYMENT"
    PARTIAL_PAYMENT = "PARTIAL_PAYMENT"
    MARK_PAID = "MARK_PAID"
    FULFILL_INVOICE = "FULFILL_INVOICE"
    CANCEL_INVOICE = "CANCEL_INVOICE"

    # -------- DISCOUNTS --------
    CREATE_DISCOUNT = "CREATE_DISCOUNT"
    UPDATE_DISCOUNT = "UPDATE_DISCOUNT"
    DEACTIVATE_DISCOUNT = "DEACTIVATE_DISCOUNT"
    REACTIVATE_DISCOUNT = "REACTIVATE_DISCOUNT"
    ACTIVATE_DISCOUNT = "ACTIVATE_DISCOUNT"
    EXPIRE_DISCOUNT = "EXPIRE_DISCOUNT"

    # -------- STOCK TRANSFERS --------
    CREATE_STOCK_TRANSFER = "CREATE_STOCK_TRANSFER"
    UPDATE_STOCK_TRANSFER = "UPDATE_STOCK_TRANSFER"
    COMPLETE_STOCK_TRANSFER = "COMPLETE_STOCK_TRANSFER"
    CANCEL_STOCK_TRANSFER = "CANCEL_STOCK_TRANSFER"

    # -------- COMPLAINTS --------
    CREATE_COMPLAINT = "CREATE_COMPLAINT"
    UPDATE_COMPLAINT = "UPDATE_COMPLAINT"
    UPDATE_COMPLAINT_STATUS = "UPDATE_COMPLAINT_STATUS"
    DELETE_COMPLAINT = "DELETE_COMPLAINT"
    