from enum import Enum


class ActivityCode(str, Enum):
    LOGIN = "LOGIN"
    LOGOUT = "LOGOUT"

    CREATE_USER = "CREATE_USER"

    UPDATE_USER_ROLE = "UPDATE_USER_ROLE"
    UPDATE_USER_EMAIL = "UPDATE_USER_EMAIL"
    UPDATE_USER_PASSWORD = "UPDATE_USER_PASSWORD"

    ACTIVATE_USER = "ACTIVATE_USER"
    DEACTIVATE_USER = "DEACTIVATE_USER"
    REACTIVATE_USER = "REACTIVATE_USER"

    CREATE_CUSTOMER = "CREATE_CUSTOMER"
    UPDATE_CUSTOMER = "UPDATE_CUSTOMER"
    DEACTIVATE_CUSTOMER = "DEACTIVATE_CUSTOMER"
    REACTIVATE_CUSTOMER = "REACTIVATE_CUSTOMER"