from enum import Enum


class ErrorCode(str, Enum):
    # -------- GENERIC --------
    INTERNAL_ERROR = "INTERNAL_ERROR"
    VALIDATION_ERROR = "VALIDATION_ERROR"
    NOT_FOUND = "NOT_FOUND"
    PERMISSION_DENIED = "PERMISSION_DENIED"
    UNAUTHORIZED = "UNAUTHORIZED"
    CONFLICT = "CONFLICT"

    # -------- AUTH --------
    INVALID_CREDENTIALS = "INVALID_CREDENTIALS"
    TOKEN_EXPIRED = "TOKEN_EXPIRED"
    TOKEN_INVALID = "TOKEN_INVALID"

    # -------- USERS --------
    USER_NOT_FOUND = "USER_NOT_FOUND"
    USER_EMAIL_EXISTS = "USER_EMAIL_EXISTS"
    USER_INACTIVE = "USER_INACTIVE"
    USER_ROLE_INVALID = "USER_ROLE_INVALID"
    USER_VERSION_CONFLICT = "USER_VERSION_CONFLICT"

    # -------- CUSTOMERS --------
    CUSTOMER_NOT_FOUND = "CUSTOMER_NOT_FOUND"
    CUSTOMER_EMAIL_EXISTS = "CUSTOMER_EMAIL_EXISTS"
    CUSTOMER_VERSION_CONFLICT = "CUSTOMER_VERSION_CONFLICT"
    CUSTOMER_CODE_EXISTS = "CUSTOMER_CODE_EXISTS"
    
    # -------- SUPPLIERS --------
    SUPPLIER_NOT_FOUND = "SUPPLIER_NOT_FOUND"
    SUPPLIER_NAME_EXISTS = "SUPPLIER_NAME_EXISTS"
    SUPPLIER_CODE_EXISTS = "SUPPLIER_CODE_EXISTS"
    SUPPLIER_VERSION_CONFLICT = "SUPPLIER_VERSION_CONFLICT"

