from enum import Enum


class ErrorCode(str, Enum):
    # -------- GENERIC --------
    INTERNAL_ERROR = "INTERNAL_ERROR"
    VALIDATION_ERROR = "VALIDATION_ERROR"
    NOT_FOUND = "NOT_FOUND"
    PERMISSION_DENIED = "PERMISSION_DENIED"
    UNAUTHORIZED = "UNAUTHORIZED"
    CONFLICT = "CONFLICT"

    # -------- AUTH --------
    INVALID_CREDENTIALS = "INVALID_CREDENTIALS"
    TOKEN_EXPIRED = "TOKEN_EXPIRED"
    TOKEN_INVALID = "TOKEN_INVALID"

    # -------- USERS --------
    USER_NOT_FOUND = "USER_NOT_FOUND"
    USER_EMAIL_EXISTS = "USER_EMAIL_EXISTS"
    USER_INACTIVE = "USER_INACTIVE"
    USER_ROLE_INVALID = "USER_ROLE_INVALID"
    USER_VERSION_CONFLICT = "USER_VERSION_CONFLICT"

    # -------- CUSTOMERS --------
    CUSTOMER_NOT_FOUND = "CUSTOMER_NOT_FOUND"
    CUSTOMER_EMAIL_EXISTS = "CUSTOMER_EMAIL_EXISTS"
    CUSTOMER_VERSION_CONFLICT = "CUSTOMER_VERSION_CONFLICT"
    CUSTOMER_CODE_EXISTS = "CUSTOMER_CODE_EXISTS"
    
    # -------- SUPPLIERS --------
    SUPPLIER_NOT_FOUND = "SUPPLIER_NOT_FOUND"
    SUPPLIER_NAME_EXISTS = "SUPPLIER_NAME_EXISTS"
    SUPPLIER_CODE_EXISTS = "SUPPLIER_CODE_EXISTS"
    SUPPLIER_VERSION_CONFLICT = "SUPPLIER_VERSION_CONFLICT"

    # -------- PRODUCTS --------
    PRODUCT_NOT_FOUND = "PRODUCT_NOT_FOUND"
    PRODUCT_SKU_EXISTS = "PRODUCT_SKU_EXISTS"
    PRODUCT_VERSION_CONFLICT = "PRODUCT_VERSION_CONFLICT"
    PRODUCT_NAME_EXISTS = "PRODUCT_NAME_EXISTS"

    # -------- DISCOUNTS --------
    DISCOUNT_NOT_FOUND = "DISCOUNT_NOT_FOUND"
    DISCOUNT_CODE_EXISTS = "DISCOUNT_CODE_EXISTS"
    DISCOUNT_VERSION_CONFLICT = "DISCOUNT_VERSION_CONFLICT"
    DISCOUNT_INVALID_RANGE = "DISCOUNT_INVALID_RANGE"
    DISCOUNT_INVALID_VALUE = "DISCOUNT_INVALID_VALUE"
    DISCOUNT_ALREADY_ACTIVE = "DISCOUNT_ALREADY_ACTIVE"
    DISCOUNT_EXPIRED = "DISCOUNT_EXPIRED"
    DISCOUNT_USAGE_LIMIT_REACHED = "DISCOUNT_USAGE_LIMIT_REACHED"
    DISCOUNT_DATE_OVERLAP = "DISCOUNT_DATE_OVERLAP"

    # -------- INVENTORY LOCATIONS --------
    LOCATION_NOT_FOUND = "LOCATION_NOT_FOUND"
    LOCATION_CODE_EXISTS = "LOCATION_CODE_EXISTS"
    LOCATION_VERSION_CONFLICT = "LOCATION_VERSION_CONFLICT"
    LOCATION_IN_USE = "LOCATION_IN_USE"
    LOCATION_HAS_STOCK = "LOCATION_HAS_STOCK"
    LOCATION_CANNOT_DEACTIVATE = "LOCATION_CANNOT_DEACTIVATE"
    LOCATION_CANNOT_ACTIVATE = "LOCATION_CANNOT_ACTIVATE"

    # -------- GRNS --------
    GRN_NOT_FOUND = "GRN_NOT_FOUND"
    GRN_INVALID_STATUS = "GRN_INVALID_STATUS"
    GRN_BILL_EXISTS = "GRN_BILL_EXISTS"
    GRN_VERSION_CONFLICT = "GRN_VERSION_CONFLICT"
    GRN_EMPTY_ITEMS = "GRN_EMPTY_ITEMS"
    GRN_INVALID_SUPPLIER = "GRN_INVALID_SUPPLIER"
    GRN_INVALID_LOCATION = "GRN_INVALID_LOCATION"
    GRN_INVALID_PRODUCT = "GRN_INVALID_PRODUCT"
    GRN_DUPLICATE_ITEMS = "GRN_DUPLICATE_ITEMS"
    NO_CHANGES_DETECTED = "NO_CHANGES_DETECTED"


    

    

